### ISSUE TITLE
Corrupt Font files

### ISSUE THREAD

**Issue by rubensa** [webjars/bootswatch#19]
The font files included at **/META-INF/resources/webjars/bootswatch/3.3.5/fonts** are corrupt.

In **bootswatch-3.3.5.jar** (/META-INF/resources/webjars/bootswatch/3.3.5/fonts):
* glyphicons-halflings-regular.eot: **68 bytes**
* glyphicons-halflings-regular.svg: **68 bytes**
* glyphicons-halflings-regular.ttf: **68 bytes**
* glyphicons-halflings-regular.woff: **68 bytes**
* glyphicons-halflings-regular.woff2: **70 bytes**

Same files in **bootstrap-3.3.5.jar** (/META-INF/resources/webjars/bootstrap/3.3.5/fonts/):
* glyphicons-halflings-regular.eot: **21,1 kB**
* glyphicons-halflings-regular.svg: **108,7 kB**
* glyphicons-halflings-regular.ttf: **45,4 kB**
* glyphicons-halflings-regular.woff: **23,4 kB**
* glyphicons-halflings-regular.woff2: **18,0 kB**

**Comment by rubensa** [comment]
I think that build should use bootswatch v3.3.5+1 release (or better v3.3.5+4 that is latest v.3.3.5 release) as it corrects bug https://github.com/thomaspark/bootswatch/issues/483 (symliks used to reference font files)

**Comment by jamesward** [comment]
This looks like it was an upstream issue.  So closing.  `3.3.5+4` will be released shortly.
