### ISSUE TITLE
Update to v4.0.0

### ISSUE THREAD

**Issue by aparsons** [webjars/bootswatch#22]
https://github.com/thomaspark/bootswatch/releases/tag/v4.0.0

**Comment by SackCastellon** [comment]
Version 4.0.0 is not available in the Maven repository, the latest version available is 3.3.7

![image](https://user-images.githubusercontent.com/5330355/38624490-781edd0c-3da8-11e8-8aae-a63427fa2580.png)

**Comment by jamesward** [comment]
Whoops.  I've deploying that now.
