### ISSUE TITLE
bootswatch 5.0.2 is not available in maven central repository

### ISSUE THREAD

**Issue by karstenroethig** [webjars/bootswatch#30]
Although it has been released, bootswatch 5.0.2 is not available in the maven central repository.

I'm trying to include bootswatch-darkly 5.0.2 in my project, but it's not available: https://search.maven.org/artifact/org.webjars/bootswatch-darkly

**Comment by jamesward** [comment]
Whoops. This one requires a manual Maven Central release and I forgot to do it.  Doing it now.  Sorry for the hassle.

**Comment by karstenroethig** [comment]
Sorry for bothering you again. It doesn't look like anything has changed.
Bootswatch 5.0.2 is still not available in the maven central repository.

**Comment by jamesward** [comment]
I'm having issues getting the release recreated. :( sorry for the delay. I'll let you know when I get it figured out.

**Comment by jamesward** [comment]
Looks like I got this working so it should be released soon.
